name: PR CI

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [ main, master, develop ]
    paths-ignore:
      - '**.md'
      - 'docs/**'

concurrency:
  group: pr-${{ github.event.pull_request.number }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    runs-on: self-hosted
    if: ${{ github.event.pull_request.draft == false }} # no test on draft

    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10']
        os: [linux]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run pre-commit on diff only
        if: ${{ github.event_name == 'pull_request' }}
        shell: bash -l {0}
        run: |
          git fetch origin ${{ github.base_ref }}
          /root/miniconda3/envs/internutopia/bin/pre-commit run --from-ref origin/${{ github.base_ref }} --to-ref HEAD

      - name: Run tests
        shell: bash -l {0}
        run: |

          # ensure a writable local data tree inside the checkout
          [ -L data ] && rm -f data        # remove if 'data' is an old symlink
          [ -d data ] || mkdir -p data     # create if missing
          chmod u+w data || true

          mkdir -p data/vln_pe             # make parent dir for the symlink
          rm -f data/vln_pe/traj_data      # remove old symlink/file if any
          ln -s /shared/smartbot/vln-pe/kujiale/grnavigation/data/lerobot/kujiale data/vln_pe/traj_data

          # other links (make sure parents exist first)
          rm -f data/mp3d_data
          ln -s /cpfs/user/wangyukai/mp3d_data data

          rm -f interiornav_data
          ln -s /cpfs/user/wangyukai/kujiale_data interiornav_data

          rm -f checkpoints
          ln -s /cpfs/user/wangyukai/checkpoints checkpoints

          # run tests
          /root/miniconda3/envs/internutopia/bin/python -c "import torch,sys;print(sys.executable);print('cuda:',torch.cuda.is_available())"
          /root/miniconda3/envs/internutopia/bin/python -m pytest -q -W ignore
