name: PR CI

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [ main, master, develop ]
    paths-ignore:
      - '**.md'
      - 'docs/**'

concurrency:
  group: pr-${{ github.event.pull_request.number }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    runs-on: self-hosted
    if: ${{ github.event.pull_request.draft == false }} # no test on draft

    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10']
        os: [linux]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Run pre-commit on diff only
        if: ${{ github.event_name == 'pull_request' }}
        shell: bash -l {0}
        run: |
          conda activate internutopia
          git fetch origin ${{ github.base_ref }}
          pre-commit run --from-ref origin/${{ github.base_ref }} --to-ref HEAD

      - name: Run tests
        shell: bash -l {0}
        run: |
          conda activate internutopia
          pytest -q -W ignore
